language: go
sudo: false

os:
  - linux

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

before_install:
  - go get -u -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on

after_success:
  - bash <(curl -s https://codecov.io/bash)
