language: go
sudo: false

os:
  - linux

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

before_install:
  - go get -u -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env: GO111MODULE=on

after_success:
  - bash <(curl -s https://codecov.io/bash)
